DEFAULT_CHECKPOINT_NAME = "last"

RAW_ANNOT_FOR_LOSS_NAME = ".raw"
WEIGHT_ANNOT_FOR_LOSS_NAME = ".weight"
EFF_ANNOT_FOR_LOSS_NAME = ".eff"

LOADER_TRAIN_TYPE = "train"
LOADER_VAL_TYPE = "val"
LOADER_TEST_TYPE = "test"

LR_ANNOT_FOR_OPTIMIZER_NAME = ".lr"
